### ISSUE TITLE
for more information

### ISSUE THREAD

**Issue by kiyurei** [Edwardsoen/aw-watcher-steam#1]
I downloaded python, but I don't know what you are talking about to install. I downloaded the folder but it seems to be missing something. Can you provide more detailed information?I hope I'm not disturbing you.

I used the translation software to talk with you.

**Comment by Edwardsoen** [comment]
Hello, this is an extension for <a href = "https://activitywatch.net/">Activitywatch</a>.  you need to have Activitywatch running for this to work. 

Once you have it running you can 
1. clone this repository
2. cd to the folder 
3. run ``` pip install . ```  
4. follow the rest of the instruction provided 

用英语不方便的话用中文说也可以 😁

**Comment by kiyurei** [comment]
题外话，你最后让我说中文吓到我了，你会中文吗？

**Comment by Edwardsoen** [comment]
嗯嗯可以的
